id: f74b2a4ca8b64f198e30ce84da7638e5
initial_creation_type: ocr
source_metadata:
  volumes:
    43de0d665d1a40c080528885ecf88e28:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ''
      total_pages: 1902
      volume_number: 26
